//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covid19_Vaccine
    {
        public string IdPatient { get; set; }
        public System.DateTime DateOfVaccine { get; set; }
        public int NumberOfVaccine { get; set; }
        public string Creator_ { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
